version: "3.0"

services:
  nest:
    container_name: nest
    build: ./backend
    env_file:
      - .env
    ports:
      - "$NEST_PORT:$NEST_PORT"
    volumes:
      - "$VOLUMEPATH/backend:/var/backend"
    networks:
      - intra
    depends_on:
      - redis
      - postgres

  # this is not a database
  # this is in-memory message broker
  redis:
    container_name: mb
    image: redis:7.0-alpine
    ports:
      - "6379:6379" 
    networks:
      - intra

  postgres:
    container_name: pg
    image: postgres
    ports:
      - "5432:5432" #http://localhost:5555
    environment:
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: "$POSTGRES_DB"
      TZ: "GMT+9"
      PGTZ: "GMT+9"
    volumes:
      - "$VOLUMEPATH/postgres:/var/lib/postgresql/data"
    networks:
      - intra

  react:
    container_name: react
    build: ./frontend
    env_file:
      - .env
    volumes:
      - "$VOLUMEPATH/frontend:/var/frontend"
    ports:
      - "$REACT_PORT:10003"
    networks:
      - intra

networks:
  intra:
